---
# Name of your project, will also be the vagrant box name
project_name: "declutter"

# Main hostname through which the vagrant box will be accessible
hostname: "declutter.lo"
# Alternative hostnames through which you want to access the vagrant box
hostnames: []

# Ports you want forwared to your host. See https://www.vagrantup.com/docs/networking/forwarded_ports.html
# for details.
forwarded_ports: {
    "80": "8080",    # HTTP
    "443": "8443",   # HTTPS
    "3000": "3000",  # BrowserSync default port
}

# By default Vagrant managed different IPs for all boxes. But you can force it
# here if you want. WARNING, this parameter will not guarantee that your box
# will be accessible at this IP depending on your network configuration or
# provider choice.
box_ip: "10.43.44.45"

# Name of the database to create for your project if you include the
# MySQL or PostgreSQL role
database_name: "declutter"

# Root directory of your project for the webserver and other purposes
root_directory: "/vagrant/public/"

php_version: "7.2"
