---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }
    - { role: composer }
    - { role: nodejs }
    - { role: php-xdebug }
    - { role: mysql }
    - { role: php-apache }    # PHP using Apache and mod-php
    - { role: apache }         # Apache for basic HTML website

  tasks:
    - name: Ensure php7.2 packages needed for Laravel are installed
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - php7.2-zip
        - php7.2-mbstring
        - php7.2-mysql
        - php7.2-xml
      notify: restart apache

    - name: Fix cache permission
      file:
        path: "{{ root_directory }}../bootstrap/cache"
        state: directory
        mode: 0777
        recurse: yes

    - name: Fix storage permission
      file:
        path: "{{ root_directory }}../storage"
        state: directory
        mode: 0777
        recurse: yes

    - name: Install Laravel packages via composer
      shell: cd {{ root_directory }}../ && composer --quiet install

    - name: Ensure chromedriver is installed
      apt: pkg=chromedriver state=present
      sudo: yes

    - name: Set artisan command executable
      file: dest={{ root_directory }}../artisan mode=a+wrx

    - name: Copy the env file
      shell: cp -n {{ root_directory }}../.env.example {{ root_directory }}../.env

    - name: Create Laravel application key
      shell: "{{ root_directory }}../artisan key:generate"

    - name: Create Laravel application key
      shell: "{{ root_directory }}../artisan migrate --seed"
